---
title: "CNN"
author: "Alex Liu"
date: "2023-04-17"
output: html_document
---

```{r warning=F, message=F}
library(EBImage)
library(tidyverse)
library(pracma)
library(randomForest)
library(ggimage)
```

```{r}
labels = list.files("../bio_data/Biotechnology/data_processed/cell_images/")
cell_boundaries_raw = read.csv("../bio_data/Biotechnology/data_processed/cell_boundaries.csv.gz")

cluster_ids = list()

for (i in 1:length(labels)) {
  
  cluster_file = list.files(paste0("../bio_data/Biotechnology/data_processed/cell_images/", labels[i]))
  
  cluster_ids[i] <- list(gsub(".*cell_|.png", "", cluster_file))
}

cluster_imgs = list()

for (i in 1:length(labels)) {
  
  cluster_file = list.files(paste0("../bio_data/Biotechnology/data_processed/cell_images/", labels[i]), full.names=T)
  
  cluster_imgs[i] <- list(sapply(cluster_file, readImage, simplify = F))

}
```

```{r}
get_inside = function(cellID, img, cell_boundaries) {
  
  cell_boundary = cell_boundaries |>
    filter(cell_id %in% cellID)
  
  # rescale the boundary according to the pixels
  pixels = dim(img)
  cell_boundary$vertex_x_scaled <- 1+((cell_boundary$vertex_x - min(cell_boundary$vertex_x))/0.2125)
  cell_boundary$vertex_y_scaled <- 1+((cell_boundary$vertex_y - min(cell_boundary$vertex_y))/0.2125)
  
  # identify which pixels are inside or outside of the cell segment using inpolygon
  pixel_locations = expand.grid(seq_len(nrow(img)), seq_len(ncol(img)))
  
  pixels_inside = inpolygon(x = pixel_locations[,1],
                            y = pixel_locations[,2],
                            xp = cell_boundary$vertex_x_scaled,
                            yp = cell_boundary$vertex_y_scaled,
                            boundary = TRUE)
  
  img_inside = img
  img_inside@.Data <- matrix(pixels_inside, nrow = nrow(img), ncol = ncol(img))
  
  return(img_inside)
}

mask_resize = function(img, img_inside, w = 50, h = 50) {
  
  img_mask = img*img_inside
  
  # then, transform the masked image to the same number of pixels, 50x50
  img_mask_resized = resize(img_mask, w, h)
  
  return(img_mask_resized)
}
```

```{r}
cluster_imgs_masked_resized = list()

for (i in 1:length(labels)) {
  cell_boundaries = cell_boundaries_raw |>
    filter(cell_id %in% cluster_ids[[i]])
    
  cluster_imgs_inside <- mapply(get_inside, cluster_ids[[i]], cluster_imgs[[i]], MoreArgs = list(cell_boundaries = cell_boundaries), SIMPLIFY = FALSE)
  
  cluster_imgs_masked_resized[i] = list(mapply(mask_resize, cluster_imgs[[i]], cluster_imgs_inside, MoreArgs = list(w = 64, h = 64), SIMPLIFY = FALSE))

}
```

```{r}
set.seed(63)
library(keras)
#use_condaenv("r-reticulate", required=T)
tensorflow::set_random_seed(63)

imgs_masked_resize_64 = do.call(c, cluster_imgs_masked_resized)

num_images = length(imgs_masked_resize_64)
img_names = names(imgs_masked_resize_64)

x = array(dim = c(num_images, 64, 64, 1))

# Centering Intensity values
for (i in 1:num_images) {
  x[i,,,1] <- imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data)
}

input_shape = dim(x)[2:4]
```

```{r}
lr = 0.001
# Default Model
model_function_binary <- function(learning_rate = lr) {
  
  k_clear_session()
  
  model <- keras_model_sequential() %>%
    layer_conv_2d(filters = 32, kernel_size = c(3,3), activation = 'relu', input_shape = input_shape) %>% 
    layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
    layer_conv_2d(filters = 64, kernel_size = c(3,3), activation = 'relu') %>% 
    layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
    layer_dropout(rate = 0.25) %>% 
    layer_flatten() %>% 
    layer_dense(units = 128, activation = 'relu') %>% 
    layer_dropout(rate = 0.5) %>% 
    layer_dense(units = 64) %>% 
    layer_dropout(rate = 0.5) %>% 
    layer_dense(units = 28, activation = 'softmax')
  
  model %>% compile(
    loss = "binary_crossentropy",
    optimizer = optimizer_adam(learning_rate = learning_rate),
    metrics = "accuracy"
  )
  
  return(model)
  
}

# Categorical Crossentropy
model_function <- function(learning_rate = lr) {
  
  k_clear_session()
  
  model <- keras_model_sequential() %>%
    layer_conv_2d(filters = 32, kernel_size = c(3,3), activation = 'relu', input_shape = input_shape) %>% 
    layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
    layer_conv_2d(filters = 64, kernel_size = c(3,3), activation = 'relu') %>% 
    layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
    layer_dropout(rate = 0.25) %>% 
    layer_flatten() %>% 
    layer_dense(units = 128, activation = 'relu') %>% 
    layer_dropout(rate = 0.5) %>% 
    layer_dense(units = 64) %>% 
    layer_dropout(rate = 0.5) %>% 
    layer_dense(units = 28, activation = 'softmax')
  
  model %>% compile(
    loss = "categorical_crossentropy",
    optimizer = optimizer_adam(learning_rate = learning_rate),
    metrics = "accuracy"
  )
  
  return(model)
  
}

# RMSprop
model_function_rmsprop <- function(learning_rate = lr) {
  
  k_clear_session()
  
  model <- keras_model_sequential() %>%
    layer_conv_2d(filters = 32, kernel_size = c(3,3), activation = 'relu', input_shape = input_shape) %>% 
    layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
    layer_conv_2d(filters = 64, kernel_size = c(3,3), activation = 'relu') %>% 
    layer_max_pooling_2d(pool_size = c(2, 2)) %>% 
    layer_dropout(rate = 0.25) %>% 
    layer_flatten() %>% 
    layer_dense(units = 128, activation = 'relu') %>% 
    layer_dropout(rate = 0.5) %>% 
    layer_dense(units = 64) %>% 
    layer_dropout(rate = 0.5) %>% 
    layer_dense(units = 28, activation = 'softmax')
  
  model %>% compile(
    loss = "binary_crossentropy",
    optimizer = optimizer_rmsprop(learning_rate = learning_rate),
    metrics = "accuracy"
  )
  
  return(model)
  
}
```


```{r training_data}
times = c()

for (i in 1:length(labels)) {
  times[i] = length(cluster_ids[[i]])
}

y = factor(rep(labels, times = times))

batch_size <- 32
epochs <- 100

yy = model.matrix(~ y - 1)

set.seed(63)

# Shuffle data into training and test set

shuf_ind <- sample(1:dim(x)[1], dim(x)[1]*0.8)
shuf_x_train <- x[shuf_ind, , ,]
shuf_x_train <- array(shuf_x_train, dim = c(dim(shuf_x_train)[1], dim(shuf_x_train)[2], dim(shuf_x_train)[3], 1))

shuf_x_test <- x[-shuf_ind, , ,]
shuf_x_test <- array(shuf_x_test, dim = c(dim(shuf_x_test)[1], dim(shuf_x_test)[2], dim(shuf_x_test)[3], 1))

shuf_yy_train <- yy[shuf_ind, ]
shuf_yy_test <- yy[-shuf_ind, ]
```

```{r class_weights}
# Addressing class imbalance through using class weights
clcount <- table(y[shuf_ind])

class_weight <- list(
  "0" = sum(clcount) / (28*clcount["cluster_1"]),
  "1" = sum(clcount) / (28*clcount["cluster_10"]),
  "2" = sum(clcount) / (28*clcount["cluster_11"]),
  "3" = sum(clcount) / (28*clcount["cluster_12"]),
  "4" = sum(clcount) / (28*clcount["cluster_13"]),
  "5" = sum(clcount) / (28*clcount["cluster_14"]),
  "6" = sum(clcount) / (28*clcount["cluster_15"]),
  "7" = sum(clcount) / (28*clcount["cluster_16"]),
  "8" = sum(clcount) / (28*clcount["cluster_17"]),
  "9" = sum(clcount) / (28*clcount["cluster_18"]),
  "10" = sum(clcount) / (28*clcount["cluster_19"]),
  "11" = sum(clcount) / (28*clcount["cluster_2"]),
  "12" = sum(clcount) / (28*clcount["cluster_20"]),
  "13" = sum(clcount) / (28*clcount["cluster_21"]),
  "14" = sum(clcount) / (28*clcount["cluster_22"]),
  "15" = sum(clcount) / (28*clcount["cluster_23"]),
  "16" = sum(clcount) / (28*clcount["cluster_24"]),
  "17" = sum(clcount) / (28*clcount["cluster_25"]),
  "18" = sum(clcount) / (28*clcount["cluster_26"]),
  "19" = sum(clcount) / (28*clcount["cluster_27"]),
  "20" = sum(clcount) / (28*clcount["cluster_28"]),
  "21" = sum(clcount) / (28*clcount["cluster_3"]),
  "22" = sum(clcount) / (28*clcount["cluster_4"]),
  "23" = sum(clcount) / (28*clcount["cluster_5"]),
  "24" = sum(clcount) / (28*clcount["cluster_6"]),
  "25" = sum(clcount) / (28*clcount["cluster_7"]),
  "26" = sum(clcount) / (28*clcount["cluster_8"]),
  "27" = sum(clcount) / (28*clcount["cluster_9"])
)
```

# Model with no noise

```{r default_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = shuf_x_train,
  y = shuf_yy_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(shuf_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs, 
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_catent_cweights/training.csv")

#save_model_tf(model_catent, "cnn_catent")
#save_model_tf(model_catent, "cnn_catent_cweights")

#save_model_weights_tf(model_catent, "Image_App/models/cnn_catent_cweights_weights/")
```

```{r default_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = shuf_x_train,
  y = shuf_yy_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(shuf_x_train)[1]*0.8) %/% batch_size,
  #class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_binary_cweights/training.csv")

#save_model_tf(model_binary, "models/cnn_binary")
#save_model_tf(model_binary, "models/cnn_binary_cweights")
```

```{r default_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = shuf_x_train,
  y = shuf_yy_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(shuf_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop")
```

# Models with noise

## 0.2 mean gaussian noise

```{r noise}
add_gaussian_noise <- function(images, mean = 0, sd = 0.1) {
  noisy_images <- array(0, dim = dim(images))
  for (i in 1:nrow(images)) {
    noisy_images[i, ] <- images[i,] + rnorm(1, mean, sd)
  }
  return(noisy_images)
}
```

```{r}
temp <- add_gaussian_noise(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), mean = 0.2)
display(temp, method = "raster")
```

```{r noise_training_02}
# Only apply noise to training set
noise_x = array(dim = c(num_images, 64, 64, 1))
set.seed(20)
for (i in 1:num_images) {
  noise_x[i,,,1] <- add_gaussian_noise(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), mean = 0.2)
}

# Choose from noise set, we only apply noise to the training set
# Same indicies as shuf_x_train
noise_x = noise_x[shuf_ind, , ,]
noise_x <- array(noise_x, dim = c(dim(noise_x)[1], dim(noise_x)[2], dim(noise_x)[3], 1))

# Combine both,
noise_x_train = abind(shuf_x_train, noise_x, along = 1)

# New training y set by doubling original y train and shuffle indicies
noise_y_train <- abind(shuf_yy_train, shuf_yy_train, along = 1)
```

```{r noise_04_catent}
# test sets remain untouched
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = noise_x_train,
  y = noise_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(noise_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_noise02/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_catent_cweights_noise02/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_noise02")
#save_model_tf(model_catent, "models/cnn_catent_cweights_noise02")
```

```{r noise_02_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = noise_x_train,
  y = noise_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(noise_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary_noise02/training.csv")
write.csv(tempdf, "Image_App/models/cnn_binary_cweights_noise02/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_noise02")
#save_model_tf(model_binary, "models/cnn_binary_cweights_noise02")
```

```{r noise_02_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = noise_x_train,
  y = noise_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(noise_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_noise02/training.csv")
write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_noise02/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_noise02")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_noise02")
```

## 0.8 mean gaussian noise

```{r}
temp <- add_gaussian_noise(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), mean = 0.8)
display(temp, method = "raster")
```

```{r noise_training_08}
noise_x = array(dim = c(num_images, 64, 64, 1))

set.seed(40)
for (i in 1:num_images) {
  noise_x[i,,,1] <- add_gaussian_noise(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), mean = 0.8)
}

noise_x = noise_x[shuf_ind, , ,]
noise_x <- array(noise_x, dim = c(dim(noise_x)[1], dim(noise_x)[2], dim(noise_x)[3], 1))

noise_x_train = abind(shuf_x_train, noise_x, along = 1)

noise_y_train <- abind(shuf_yy_train, shuf_yy_train, along = 1)
```

```{r noise_08_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = noise_x_train,
  y = noise_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(noise_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_noise08/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_catent_cweights_noise08/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_noise08")
#save_model_tf(model_catent, "models/cnn_catent_cweights_noise08")
```

```{r noise_08_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = noise_x_train,
  y = noise_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(noise_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary_noise08/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_binary_cweights_noise08/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_noise08")
#save_model_tf(model_binary, "models/cnn_binary_cweights_noise08")
```

```{r noise_08_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = noise_x_train,
  y = noise_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(noise_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_noise08/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_noise08/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_noise08")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_noise08")
```

## Random Noise

```{r noise_training_rand}
noise_x = array(dim = c(num_images, 64, 64, 1))
noise_ls = c(0.2, 0.4, 0.6, 0.8, 1)

set.seed(40)
noise_level = sample(1:length(noise_ls), num_images, replace=T)
for (i in 1:num_images) {
  noise_x[i,,,1] <- add_gaussian_noise(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), mean = noise_ls[noise_level[i]])
}

noise_x = noise_x[shuf_ind, , ,]
noise_x <- array(noise_x, dim = c(dim(noise_x)[1], dim(noise_x)[2], dim(noise_x)[3], 1))

noise_x_train = abind(shuf_x_train, noise_x, along = 1)

noise_y_train <- abind(shuf_yy_train, shuf_yy_train, along = 1)
```

```{r noise_rand_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = noise_x_train,
  y = noise_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(noise_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_noiserand/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_catent_cweights_noiserand/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_noiserand")
#save_model_tf(model_catent, "models/cnn_catent_cweights_noiserand")
```

```{r noise_rand_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = noise_x_train,
  y = noise_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(noise_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary_noiserand/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_binary_cweights_noiserand/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_noiserand")
#save_model_tf(model_binary, "models/cnn_binary_cweights_noiserand")
```

```{r noise_rand_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = noise_x_train,
  y = noise_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(noise_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_noiserand/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_noiserand/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_noiserand")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_noiserand")
```


# Model with resolution

## 16x16 resolution

```{r}
temp <- resize(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), 16)
display(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), method = "raster")
display(temp, method = "raster")
```

```{r res_training_16}
res_x = array(dim = c(num_images, 64, 64, 1))

for (i in 1:num_images) {
  res_x[i,,,1] <- resize(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), 16)
}

res_x = res_x[shuf_ind, , ,]
res_x <- array(res_x, dim = c(dim(res_x)[1], dim(res_x)[2], dim(res_x)[3], 1))

res_x_train = abind(shuf_x_train, res_x, along = 1)

res_y_train <- abind(shuf_yy_train, shuf_yy_train, along = 1)
```

```{r res_16_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_res16/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_catent_cweights_res16/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_res16")
#save_model_tf(model_catent, "models/cnn_catent_cweights_res16")
```

```{r res_16_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary_res16/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_binary_cweights_res16/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_res16")
#save_model_tf(model_binary, "models/cnn_binary_cweights_res16")
```

```{r res_16_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_res16/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_res16/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_res16")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_res16")
```

## 32x32 resolution

```{r}
temp <- resize(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), 32)
display(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), method = "raster")
display(temp, method = "raster")
```

```{r res_training_32}
res_x = array(dim = c(num_images, 64, 64, 1))

for (i in 1:num_images) {
  res_x[i,,,1] <- resize(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), 32)
}

res_x = res_x[shuf_ind, , ,]
res_x <- array(res_x, dim = c(dim(res_x)[1], dim(res_x)[2], dim(res_x)[3], 1))

res_x_train = abind(shuf_x_train, res_x, along = 1)

res_y_train <- abind(shuf_yy_train, shuf_yy_train, along = 1)
```

```{r res_32_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_res32/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_catent_cweights_res32/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_res32")
#save_model_tf(model_catent, "models/cnn_catent_cweights_res32")
```

```{r res_32_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary_res32/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_binary_cweights_res32/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_res32")
#save_model_tf(model_binary, "models/cnn_binary_cweights_res32")
```

```{r res_32_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_res32/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_res32/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_res32")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_res32")
```

## Random resolution

```{r res_training_rand}
res_x = array(dim = c(num_images, 64, 64, 1))

# Choose randomly from 16x16 or 32x32 resolution
set.seed(48)
res_ls = c(16, 32)
res_choice = sample(1:2, num_images, replace=TRUE)

for (i in 1:num_images) {
  res_x[i,,,1] <- resize(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), res_ls[res_choice[i]])
}

res_x = res_x[shuf_ind, , ,]
res_x <- array(res_x, dim = c(dim(res_x)[1], dim(res_x)[2], dim(res_x)[3], 1))

res_x_train = abind(shuf_x_train, res_x, along = 1)

res_y_train <- abind(shuf_yy_train, shuf_yy_train, along = 1)
```

```{r res_rand_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_res_rand/training.csv")
write.csv(tempdf, "Image_App/models/cnn_catent_cweights_res_rand/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_res_rand")
#save_model_tf(model_catent, "models/cnn_catent_cweights_res_rand")
```

```{r res_rand_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary_res_rand/training.csv")
write.csv(tempdf, "Image_App/models/cnn_binary_cweights_res_rand/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_res_rand")
#save_model_tf(model_binary, "models/cnn_binary_cweights_res_rand")
```

```{r res_rand_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_res_rand/training.csv")
write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_res_rand/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_res_rand")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_res_rand")
```

## Combine 16x16 and 32x32

```{r res_training_comb}
res_x = array(dim = c(num_images, 64, 64, 1))
res_x_2 = array(dim = c(num_images, 64, 64, 1))

for (i in 1:num_images) {
  res_x[i,,,1] <- resize(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), 16)
  
  res_x_2[i,,,1] <- resize(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), 32)
}

res_x = res_x[shuf_ind, , ,]
res_x_2 = res_x_2[shuf_ind, , ,]
res_x <- array(res_x, dim = c(dim(res_x)[1], dim(res_x)[2], dim(res_x)[3], 1))
res_x_2 <- array(res_x_2, dim = c(dim(res_x_2)[1], dim(res_x_2)[2], dim(res_x_2)[3], 1))

res_x_train = abind(shuf_x_train, res_x, res_x_2, along = 1)

res_y_train <- abind(shuf_yy_train, shuf_yy_train, shuf_yy_train, along = 1)
```

```{r res_comb_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

#save_model_tf(model_catent, "models/cnn_catent_res_comb")
save_model_tf(model_catent, "models/cnn_catent_cweights_res_comb")
```

```{r res_comb_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

#save_model_tf(model_binary, "models/cnn_binary_res_comb")
#save_model_tf(model_binary, "models/cnn_binary_cweights_res_comb")
```

```{r res_comb_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = res_x_train,
  y = res_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(res_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_res_comb")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_res_comb")
```

# Model with rotation

## 90 Degree Rotation

```{r}
temp <- rotate(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), 90)
display(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), method = "raster")
display(temp, method = "raster")
```

```{r rotate_training_90}
rotate_x = array(dim = c(num_images, 64, 64, 1))

for (i in 1:num_images) {
  rotate_x[i,,,1] <- rotate(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), 90)
}

rotate_x = rotate_x[shuf_ind, , ,]
rotate_x <- array(rotate_x, dim = c(dim(rotate_x)[1], dim(rotate_x)[2], dim(rotate_x)[3], 1))

rotate_x_train = abind(shuf_x_train, rotate_x, along = 1)

rotate_y_train <- abind(shuf_yy_train, shuf_yy_train, along = 1)
```

```{r rotate_90_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = rotate_x_train,
  y = rotate_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(rotate_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_rotate90/training.csv")
write.csv(tempdf, "Image_App/models/cnn_catent_cweights_rotate90/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_rotate90")
#save_model_tf(model_catent, "models/cnn_catent_cweights_rotate90")
```

```{r rotate_90_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = rotate_x_train,
  y = rotate_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(rotate_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary_rotate90/training.csv")
write.csv(tempdf, "Image_App/models/cnn_binary_cweights_rotate90/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_rotate90")
#save_model_tf(model_binary, "models/cnn_binary_cweights_rotate90")
```

```{r rotate_90_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = rotate_x_train,
  y = rotate_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(rotate_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_rotate90/training.csv")
write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_rotate90/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_rotate90")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_rotate90")
```

## 180 Degree Rotation (Reflection on the x-axis)

```{r}
temp <- rotate(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), 180)
display(imgs_masked_resize_64[[5]]@.Data - mean(imgs_masked_resize_64[[5]]@.Data), method = "raster")
display(temp, method = "raster")
```

```{r rotate_training_180}
rotate_x = array(dim = c(num_images, 64, 64, 1))

for (i in 1:num_images) {
  rotate_x[i,,,1] <- rotate(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), 180)
}

rotate_x = rotate_x[shuf_ind, , ,]
rotate_x <- array(rotate_x, dim = c(dim(rotate_x)[1], dim(rotate_x)[2], dim(rotate_x)[3], 1))

rotate_x_train = abind(shuf_x_train, rotate_x, along = 1)

rotate_y_train <- abind(shuf_yy_train, shuf_yy_train, along = 1)
```

```{r rotate_180_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = rotate_x_train,
  y = rotate_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(rotate_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_rotate180/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_catent_cweights_rotate180/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_rotate180")
#save_model_tf(model_catent, "models/cnn_catent_cweights_rotate180")
```

```{r rotate_180_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = rotate_x_train,
  y = rotate_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(rotate_x_train)[1]*0.8) %/% batch_size,
  #class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
write.csv(tempdf, "Image_App/models/cnn_binary_rotate180/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_binary_cweights_rotate180/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_rotate180")
#save_model_tf(model_binary, "models/cnn_binary_cweights_rotate180")
```

```{r rotate_180_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = rotate_x_train,
  y = rotate_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(rotate_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_rotate180/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_rotate180/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_rotate180")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_rotate180")
```

## Random Rotation

```{r rotate_training_random}
rotate_x = array(dim = c(num_images, 64, 64, 1))
set.seed(90)
angle = sample(1:359, num_images, replace=T)

for (i in 1:num_images) {
  rotate_x[i,,,1] <- resize(rotate(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), angle[i]), 64, 64)
}

rotate_x = rotate_x[shuf_ind, , ,]
rotate_x <- array(rotate_x, dim = c(dim(rotate_x)[1], dim(rotate_x)[2], dim(rotate_x)[3], 1))

rotate_x_train = abind(shuf_x_train, rotate_x, along = 1)

rotate_y_train <- abind(shuf_yy_train, shuf_yy_train, along = 1)
```

```{r rotate_rand_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = rotate_x_train,
  y = rotate_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(rotate_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_rotaterand/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_catent_cweights_rotaterand/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_rotaterand")
#save_model_tf(model_catent, "models/cnn_catent_cweights_rotaterand")
```

```{r rotate_rand_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = rotate_x_train,
  y = rotate_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(rotate_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary_rotaterand/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_binary_cweights_rotaterand/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_rotaterand")
#save_model_tf(model_binary, "models/cnn_binary_cweights_rotaterand")
```

```{r rotate_rand_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = rotate_x_train,
  y = rotate_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(rotate_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_rotaterand/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_rotaterand/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_rotaterand")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_rotaterand")
```

# Combined Model

```{r combined_training}
rotate_x = noise_x = res_x = array(dim = c(num_images, 64, 64, 1))

set.seed(90)
# Random Rotation
angle = sample(1:359, num_images, replace=T)
# Random Noise
noise_ls = c(0.2, 0.4, 0.6, 0.8, 1)
noise_level = sample(1:length(noise_ls), num_images, replace=T)
# Random Resolution
res_ls = c(16, 32)
res_choice = sample(1:2, num_images, replace=TRUE)

for (i in 1:num_images) {
  rotate_x[i,,,1] <- resize(rotate(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), 180), 64, 64)
  noise_x[i,,,1] <- add_gaussian_noise(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), mean = 0.2)
  res_x[i,,,1] <- resize(imgs_masked_resize_64[[i]]@.Data - mean(imgs_masked_resize_64[[i]]@.Data), res_ls[res_choice[i]])
}

rotate_x = rotate_x[shuf_ind, , ,]
rotate_x <- array(rotate_x, dim = c(dim(rotate_x)[1], dim(rotate_x)[2], dim(rotate_x)[3], 1))

noise_x = noise_x[shuf_ind, , ,]
noise_x <- array(noise_x, dim = c(dim(noise_x)[1], dim(noise_x)[2], dim(noise_x)[3], 1))

res_x = res_x[shuf_ind, , ,]
res_x <- array(res_x, dim = c(dim(res_x)[1], dim(res_x)[2], dim(res_x)[3], 1))

comb_x_train = abind(shuf_x_train, rotate_x, noise_x, res_x, along = 1)

comb_y_train <- abind(shuf_yy_train, shuf_yy_train, shuf_yy_train, shuf_yy_train, along = 1)
```

```{r comb_catent}
model_catent <- model_function()

hist <- model_catent %>% fit(
  x = comb_x_train,
  y = comb_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(comb_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

#tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_catent_comb/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_catent_cweights_comb/training.csv")

#save_model_tf(model_catent, "models/cnn_catent_comb")
#save_model_tf(model_catent, "models/cnn_catent_cweights_comb")

#save_model_weights_tf(model_catent, "Image_App/models/cnn_catent_cweights_comb_weights")
```

```{r comb_binary}
# Binary Model with and without class weights
model_binary <- model_function_binary()

hist <- model_binary %>% fit(
  x = comb_x_train,
  y = comb_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(comb_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_binary_comb/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_binary_cweights_comb/training.csv")

#save_model_tf(model_binary, "models/cnn_binary_comb")
#save_model_tf(model_binary, "models/cnn_binary_cweights_comb")
```

```{r comb_rmsprop}
model_rmsprop <- model_function_rmsprop()

hist <- model_rmsprop %>% fit(
  x = comb_x_train,
  y = comb_y_train,
  batch_size = batch_size,
  steps_per_epoch = (dim(comb_x_train)[1]*0.8) %/% batch_size,
  class_weight = class_weight,
  epochs = epochs,
  validation_data = list(shuf_x_test, shuf_yy_test),
  verbose = 2
)

plot(hist)

tempdf <- data.frame(hist$metrics)
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_comb/training.csv")
#write.csv(tempdf, "Image_App/models/cnn_rmsprop_cweights_comb/training.csv")

#save_model_tf(model_rmsprop, "models/cnn_rmsprop_cweights_comb")
#save_model_tf(model_rmsprop, "models/cnn_rmsprop_comb")

#save_model_weights_tf(model_rmsprop, "Image_App/models/cnn_rmsprop_cweights_comb/weights")
```


