---
title: "Presentation"
subtitle: "..."
author: "Image 6"
output:
  xaringan::moon_reader:
    css: ["default", "Presentation_files/assets/sydney-fonts.css", "Presentation_files/assets/sydney.css"]
    self_contained: false # if true, fonts will be stored locally
    seal: true # show a title slide with YAML information
    includes:
      in_header: "Presentation_files/assets/mathjax-equation-numbers.html"
    nature:
      beforeInit: ["Presentation_files/assets/remark-zoom.js", "https://platform.twitter.com/widgets.js"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9' # alternatives '16:9' or '4:3' or others e.g. 13:9
      navigation:
        scroll: false # disable slide transitions by scrolling
---

```{r, load_refs, echo=FALSE, cache=FALSE, message=FALSE, warning=FALSE}
library(RefManageR)
BibOptions(check.entries = FALSE, 
           bib.style = "authoryear", 
           cite.style = 'authoryear', 
           style = "markdown",
           hyperlink = FALSE, 
           dashed = FALSE)
myBib <- ReadBib("Presentation_files/assets/example.bib", check = FALSE)
top_icon = function(x) {
  icons::icon_style(
    icons::fontawesome(x),
    position = "fixed", top = 10, right = 10
  )
}

library(tidyverse)
library(gridExtra)
library(lattice)
library(ggplot2)
library(caret)
library(ggfortify)
library(kableExtra)
library(plotly)
library(dplyr)
```


## PROJECT CONTEXT 

**Motivation:**

 

**Robustness:**


**Project Question:**
- Q1: 

- Q2: 


---


## DATASET

- what it is?
- the data collection here

---


## Pre-Processing 
- workflow diagram of the pre-processing

---
class: segue-red

# Baseline Model (no augmentations)


.left[.footnote[

```
---
class: segue
```

]]


---


## Data architecture/workflow of this baseline model


---


## Results without data augmentation




---
class: segue-red

# Data Augmention


.left[.footnote[

```
---
class: segue
```

]]


---

## Choice of Data Augmentations

**Considered:**


**Choose:**
add literature review here

- noise

- rotation

- resolution


---

## Data architecture/workflow of these models 

- provide a workflow diagram 



---

## Noise PART A



---

## Noise PART B



---

## Rotation PART A


---

## Rotation PART B



---

## Resolution PART A


---

## Resolution PART B


---
class: segue-red

# Combined Model


.left[.footnote[

```
---
class: segue
```

]]

---



## Data architecture/workflow of this combined model

- provide a workflow diagram 



---

## Results of combined model




---

## Interpretation




---
class: segue-red

# Future Analysis


.left[.footnote[

```
---
class: segue
```

]]

---


## Limitations of our own analysis


---


## Future Study Recommendation



---

## References


Notes: 
- 4 workflow diagram: pre-processing, baseline model, data augmentation models, combined model?


